spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8000